{% set version = "0.9.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-see
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/see_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/see/see_{{ version }}.tar.gz
  sha256: 91a34caf7bdb55b7db8238ac89b3c17ce96ddceaee42bc78df8f4fafffd74c00

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bayestestr >=0.13.0
    - r-correlation >=0.8.3
    - r-datawizard >=0.6.4
    - r-effectsize >=0.8.2
    - r-ggplot2 >=3.4.0
    - r-insight >=0.18.8
    - r-modelbased >=0.8.5
    - r-parameters >=0.20.0
    - r-performance >=0.10.1
  run:
    - r-base
    - r-bayestestr >=0.13.0
    - r-correlation >=0.8.3
    - r-datawizard >=0.6.4
    - r-effectsize >=0.8.2
    - r-ggplot2 >=3.4.0
    - r-insight >=0.18.8
    - r-modelbased >=0.8.5
    - r-parameters >=0.20.0
    - r-performance >=0.10.1

test:
  commands:
    - $R -e "library('see')"           # [not win]
    - "\"%R%\" -e \"library('see')\""  # [win]

about:
  home: https://easystats.github.io/see/
  license: GPL-3.0-only
  summary: Provides plotting utilities supporting easystats-packages (<https://github.com/easystats/easystats>) and some extra themes, geoms, and scales for 'ggplot2'. Color scales are based on <https://www.materialui.co/colors>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - SGMartin

# Package: see
# Type: Package
# Title: Visualisation Toolbox for 'easystats' and Extra Geoms, Themes and Color Palettes for 'ggplot2'
# Version: 0.6.1
# Authors@R: c( person("Daniel", "Ludecke", role = c("aut", "cre"), email = "d.luedecke@uke.de", comment = c(ORCID = "0000-0002-8895-3206")), person("Dominique", "Makowski", email = "dom.makowski@gmail.com", role = c("aut", "inv"), comment = c(ORCID = "0000-0001-5375-9967")), person("Philip", "Waggoner", email = "philip.waggoner@gmail.com", role = c("aut", "ctb"), comment = c(ORCID = "0000-0002-7825-7573")), person("Mattan S.", "Ben-Shachar", role = c("aut"), email = "matanshm@post.bgu.ac.il", comment = c(ORCID = "0000-0002-4287-4801")), person("Brenton M.", "Wiernik", email = "brenton@wiernik.org", role = c("ctb"), comment = c(ORCID = "0000-0001-9560-6336")) )
# Maintainer: Daniel Ludecke <d.luedecke@uke.de>
# URL: https://easystats.github.io/see/
# BugReports: https://github.com/easystats/see/issues
# Description: Provides plotting utilities supporting easystats-packages (<https://github.com/easystats/easystats>) and some extra themes, geoms, and scales for 'ggplot2'. Color scales are based on <https://www.materialui.co/colors>.
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 3.5), graphics, grDevices, stats
# Imports: bayestestR, dplyr, effectsize, ggplot2, ggridges, insight, magrittr, parameters, rlang
# Suggests: brms, coda, correlation, emmeans, ggraph, ggrepel, glmmTMB, grid, gridExtra, lavaan, logspline, lme4, MASS, mclust, metafor, modelbased, NbClust, nFactors, performance, psych, randomForest, rmarkdown, rstanarm, splines, tidygraph, tidyr
# RoxygenNote: 7.1.1
# Language: en-GB
# NeedsCompilation: no
# Packaged: 2020-12-06 12:42:23 UTC; Daniel
# Author: Daniel Ludecke [aut, cre] (<https://orcid.org/0000-0002-8895-3206>), Dominique Makowski [aut, inv] (<https://orcid.org/0000-0001-5375-9967>), Philip Waggoner [aut, ctb] (<https://orcid.org/0000-0002-7825-7573>), Mattan S. Ben-Shachar [aut] (<https://orcid.org/0000-0002-4287-4801>), Brenton M. Wiernik [ctb] (<https://orcid.org/0000-0001-9560-6336>)
# Repository: CRAN
# Date/Publication: 2020-12-06 14:50:03 UTC
